blog/urls.py
from  django.urls import  path
from blog import views

urlpatterns=[
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('userlogin/',views.user_login,name='userlogin'),
    path('userlogout/',views.user_logout,name='userlogout'),
    path('signup/',views.signup,name='signup'),
    path('addpost/',views.add_post,name='addpost'),
    path('updatepost/<int:pk>/',views.update_post,name='updatepost'),
    path('deletepost/<int:id>/',views.del_post,name='delete'),
    ]

miniblog/urls.py
from django.contrib import admin
from django.urls import path,include
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home),
    path('blog/',include('blog.urls'))
]

blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title=models.CharField( max_length=150)
    desc=models.TextField()

blog/forms.py
from django.contrib.auth.forms import  UserCreationForm,AuthenticationForm,UsernameField
from django import forms
from  django.utils.translation import  gettext,gettext_lazy as _
from django.contrib.auth.models import User
from.models import Post

class signupform(UserCreationForm):
    password1=forms.CharField(label='Password',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2=forms.CharField(label='Confirm Password(again)',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model = User
        fields=['username','first_name','last_name','email']
        labels={'first_name':'First Name', 'last_name':'Last Name', 'email':'Email'}
        widgets={
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'last_name':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),
                 }
       
       
class loginform(AuthenticationForm):
    username=UsernameField(widget=forms.TextInput(attrs={'autofocus':True,'class':'form-control'}))
    password=forms.CharField(label=_('Password'),strip=False,widget=forms.PasswordInput(attrs={'autocomplete':'current-password','class':'form-control'}))


class postform(forms.ModelForm):
    class Meta:
        model=Post
        fields=['title','desc']
        labels={'title':'Title','desc':'Description'}
        widgets={
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'desc':forms.Textarea(attrs={'class':'form-control'}),
        }

blog/views.py
from django.shortcuts import render,HttpResponseRedirect
from .forms import signupform,loginform,postform
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from.models import Post
from django.contrib.auth.models import Group
# Create your views here.
def home(request):
    post=Post.objects.all()
    return render(request,'home.html',{'posts':post})

def about(request):
    return render(request,'about.html')

def contact(request):
    return render(request,'contact.html')

def dashboard(request):
    if request.user.is_authenticated:
        posts=Post.objects.all()
        user=request.user
        fullname=user.get_full_name()
        gps=user.groups.all()
        return render(request,'dashboard.html',{'posts':posts,'fullname':fullname,'groups':gps})
    else:
        return HttpResponseRedirect('/blog/userlogin/')

def user_login(request):
    if not request.user.is_authenticated:
        if request.method=="POST":
            form=loginform(request=request,data=request.POST)
            if form.is_valid():
                uname=form.cleaned_data['username']
                upass=form.cleaned_data['password']
                user=authenticate(username=uname,password=upass)
                if user is not None:
                    login(request,user)
                    messages.success(request,'Logged in Successfully')
                    return HttpResponseRedirect('/blog/dashboard/')
        else:
            form=loginform()      
        return render(request,'login.html',{'form':form})
    else:
        return HttpResponseRedirect('/blog/dashboard/')

def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')

def signup(request):
    if request.method=="POST":
        form=signupform(request.POST)
        if form.is_valid():
            messages.success(request,'Congratulations !! you have become successfully Author')
            user=form.save()
            group=Group.objects.get(name='Author')
            user.groups.add(group)
    else:
        form=signupform()
    return render(request,'signup.html',{'form':form})


def add_post(request):
    if request.user.is_authenticated:
        if request.method=="POST":
            form=postform(request.POST)
            if form.is_valid():
                title=form.cleaned_data['title']
                desc=form.cleaned_data['desc']
                post=Post(title=title,desc=desc)
                post.save()
                messages.success(request,'Post Added Successfully')
                form=postform()
        else:
            form=postform()
        return render(request,'addpost.html',{'form':form})
    else:
        return HttpResponseRedirect('/blog/userlogin/')
    
def update_post(request,pk):
    if request.user.is_authenticated:
        if request.method=="POST":
            pi=Post.objects.get(pk=pk)
            form=postform(request.POST,instance=pi)
            if form.is_valid():
                form.save()
                messages.success(request,'Post Updated Successfully')
        else:
            pi=Post.objects.get(pk=pk)
            form=postform(instance=pi)
        return render(request,'updatepost.html',{'form':form})
    else:
        return HttpResponseRedirect('/blog/userlogin/')
    
def del_post(request,id):
    if request.user.is_authenticated:
        if request.method=="POST":
            pi=Post.objects.get(pk=id)
            pi.delete()
            messages.success(request,'Post Deleted Successfully')
            return HttpResponseRedirect('/blog/dashboard/')
    else:
       return HttpResponseRedirect('/blog/dashboard/')
        

blog/templates/about.html
{% extends "base.html" %}
{% load static %}
{% block maincontent %}
<div class="col-sm-10 ">
  <h3 class="text-white mt-5">About Page</h3>
  <p>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Non blanditiis
    dolor nam placeat. Unde eaque soluta doloribus ea explicabo? Rerum
    consequuntur esse at incidunt delectus dolorem error iste doloremque quo
    omnis consectetur impedit aut sapiente placeat alias cumque, amet eum
    maiores autem obcaecati, reiciendis hic neque culpa? Aliquam, neque esse.
  </p>
  <p>
    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Autem, alias
    porro? Porro corporis tempora ad assumenda reiciendis quo, dicta sapiente
    adipisci beatae eaque vero facere, hic ducimus, quisquam expedita natus
    cupiditate nemo odit quos distinctio error debitis dolor neque perferendis.
    Dolorum at iusto debitis repellendus reprehenderit saepe esse ab voluptate?
  </p>
</div>
{% endblock maincontent %}

blog/templates/addpost.html
{% extends "base.html" %}
{% load static %}

{% block maincontent %}
<div class="col-sm-10">

    {% if messages %}
    {% for message in messages %}
    <p {% if message.tags %} class="alert alert-{{message.tags}} mb-5 mt-5"{% endif %}>{{message}}</p>  
    {% endfor %}
    {% endif %}

    <h3 class="text-white my-5">Dashboard/ Add Post</h3>
    <form action="" method="post" novalidate>
     {% csrf_token %}
     {{form.as_p}}
     <input type="submit" value="add" class="btn btn-success">
     <a href="{% url "dashboard" %}" class="btn btn-danger">Cancel</a>

    </form>
</div>
{% endblock maincontent %}

blog/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="container-fluid bg-dark">
        {% include "navbar.html" %}
    </div>

    <div class="container">
        <div class="row">
        <div class="col-sm-12">
            {% block msg %}{% endblock msg %}
        </div>
        </div>

        <div class="row">
            {% block side %}{% endblock side %}

            {% block maincontent %}{% endblock maincontent %}
        </div>
    </div>

    <script src="{% static "js/jquery.js" %}"></script>
    <script src="{% static "js/popper.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
</body>
</html>

blog/templates/contact.html
{% extends "base.html" %}
{% load static %}
{% block maincontent %}
<div class="col-sm-10 ">
  <h3 class="text-white mt-5">Contact Page</h3>
   <form action="">
        <div class="form-row">
          <div class="form-group">
            <label for="inputname">Your Name</label>
            <input type="text" class="form-control" id="inputname" />
          </div>

          <div class="form-group">
            <label for="inputemail">Your Email</label>
            <input type="email" class="form-control" id="inputemail" />
          </div> 

          <div class="form-group">
            <label for="inputsubject">Your Subject</label>
            <input type="text" class="form-control" id="inputsubject" />
          </div>

          <div class="form-group">
            <label for="inputname">Your Message</label>
            <textarea
              class="form-control"
              id="inputtextarea"
              required
            ></textarea>
          </div>
        </div>
        <button class="btn btn-info mt-3">Send</button>
      </form>
</div>
{% endblock maincontent %}

blog/templates/dashboard.html
{% extends "base.html" %}
{% load static %}

{% block msg %}
{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class="alert alert-{{message.tags}} alert-dismissable fade show mt-5 "{% endif %}>
  <strong>{{message}}</strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="close"> 
    <span aira-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}
{% endif %}
{% endblock msg %}

{% block side %}
<div class="col-sm-2 text-white my-5 text-center">
  <h4 class="my-5">Profile</h4>
  <h5>{{fullname}}</h5>
  {% for group in groups %}
  <p>{{group.name}}</p>
  {% endfor %}
</div>
{% endblock side %}


{% block maincontent %}
<div class="col-sm-12">
  <h3 class="text-white my-5">Dashboard page</h3>
  <a href="{% url "addpost" %}" class="btn btn-success">Add Post</a>
 <h4 class="text-center alert alert-info mt-3">Show Post Information</h4>
 {% if posts %}
 <table class="table table-hover bg-white">
  <thead>
    <tr class="text-center">
      <th scope="col" style="width:2%">ID</th>
      <th scope="col" style="width:28%">Title</th>
      <th scope="col" style="width:55%">Description</th>
      <th scope="col" style="width:15%">Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for post in posts %}
    <tr>
      <th scope="row">{{post.id}}</th>
      <td>{{post.title}}</td>
      <td>{{post.desc}}</td>
      <td class="text-center">
        <a href="{% url "updatepost" post.pk %}" class="btn btn-warning btn-sm">Edit</a>
        {% if perms.blog.delete_post %}
        <form action="{% url "delete" post.id %}" method="post" class="d-inline">
          {% csrf_token %}
          <input type="submit" class="btn btn-danger btn-sm" value="delete">
        </form>
        {% endif %}
      </td>
      
    </tr>
    
    {% endfor %}
  </tbody>
 </table>
 {% else %}
 <h4 class="text-center alert alert-warning">No Records</h4>
 {% endif %}
</div>

{% endblock maincontent %}

blog/templates/home.html
{% extends "base.html" %} {% load static %} {% block maincontent %}

<div class="col-sm-10 text-center">
  <h3 class="text-white mt-5">Home Page</h3>
  {% for post in posts %}
  <div class="jumbotron jumbotron-fluid jumbo-color mt-5">
    <div class="container">
      <h1 class="display-4 fw-bold">{{post.title}}</h1>
      <p class="load">{{post.desc}}</p>
    </div> 
  </div>
  {% endfor %}
</div>
{% endblock maincontent %}

blog/templates/login.html
{% extends "base.html" %} {% load static %} {% block maincontent %}
<div class="col-sm-10">
  <h3 class="text-white mt-5">Login Page</h3>
  <form action="" method="post" novalidate>
    {% csrf_token %} 
    {% for fm in form %}
    <div class="form-group">
      {{fm.label_tag}} {{fm}}<small class="text-warning">{{fm.errors|striptags}}</small>
    </div>
    {% endfor %}
    <input type="submit" class="btn btn-primary mt-3" value="login" />
     {% if form.non_field_errors %}
     {% for error in form.non_field_errors %}
    <p class="alert alert-danger my-3">{{error}}</p>
    {% endfor %} 
    {% endif %}
    
  </form>
</div>
{% endblock maincontent %}

blog/templates/logout.html
{% extends "base.html" %}
{% load static %}
{% block maincontent %}
<div class="col-sm-10 ">
  <h3 class="text-white mt-5">LogOut Page</h3>

</div>
{% endblock maincontent %}

blog/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a href="/" class="navbar-brand">Mini Blog</a>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a href="/" class="nav-link">Home</a
        >
      </li>
      <li class="nav-item active">
        <a href="{% url "about" %}" class="nav-link"
          >About</a
        >
      </li>

    <li class="nav-item active">
        <a href="{% url "contact" %}" class="nav-link"
          >Contact</a
        >
      </li>
      {% if request.user.is_authenticated %}
          <li class="nav-item active">
        <a href="{% url "dashboard" %}" class="nav-link"
          >Dashboard</a
        >
      </li>
          <li class="nav-item active">
        <a href="{% url "userlogout" %}" class="nav-link"
          >Log out</a
        >
      </li>
      {% else %}
          <li class="nav-item active">
        <a href="{% url "signup" %}" class="nav-link"
          >Sign up</a
        >
      </li>
          <li class="nav-item active">
        <a href="{% url "userlogin" %}" class="nav-link"
          >Login</a
        >
      </li>{% endif %}
    </ul>
  </div>
</nav>

blog/templates/signup.html
{% extends "base.html" %}
{% load static %}
{% block maincontent %}
<div class="col-sm-10 ">
  <h3 class="text-white mt-5">Become an Author</h3>
  {% if messages %}
  {% for message in messages %}
  <p {% if message.tags %} class="alert alert-{{message.tags}} mb-5"{% endif %}>{{message}}</p>  
  {% endfor %}
  {% endif %}
  <form action="" method='post' novalidate>
    {% csrf_token %}
    {% for fm in form  %}
    <div class="form-group mt-3">
    {{fm.label_tag}} {{fm}}<small class="text-warning">{{fm.errors}}</small>
    </div>
    {% endfor %}
    <input type="submit" value='submit' class="mt-3 btn btn-info">
    {% if form.non_field_errors %}
    {% for error in form.non_field_errors  %}
    <p class="alert alert-danger my-3">{{error}}</p>
    {% endfor %}
    {% endif %}
</form>
</div>
{% endblock maincontent %}

blog/templates/updatepost.html
{% extends "base.html" %}
{% load static %}

{% block maincontent %}
<div class="col-sm-10">

    {% if messages %}
    {% for message in messages %}
    <p {% if message.tags %} class="alert alert-{{message.tags}} mb-5 mt-5"{% endif %}>{{message}}</p>  
    {% endfor %}
    {% endif %}
    
    <h3 class="text-white my-5">Update Post</h3>
     <form action="" method="post" novalidate>
     {% csrf_token %}
     {{form.as_p}}
     <input type="submit" value="update" class="btn btn-success">
     <a href="{% url "dashboard" %}" class="btn btn-danger">Cancel</a>

    </form>
</div>
{% endblock maincontent %}